---
    
- name: Instalando o Java 8
  yum: 
    name: java-1.8.0 
    state: present
  tags:
    - deps
  
  
- name: Adicionando o repositorio do Rundeck
  yum:
    name: https://repo.rundeck.org/latest.rpm
    state: present
  tags:
    - repo


- name: Instalando o Rundeck
  yum:
    name: rundeck
    state: present
  notify:
    - Start Rundeck
  tags:
    - rundeck
